CREATE TABLE IF NOT EXISTS FASE(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FASE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ACTIVIDAD(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACTIVIDAD VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS COD_ACTIVIDAD(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODIGO_ACTIVIDAD VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS EVIDENCIA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVIDENCIA VARCHAR(50) UNIQUE NOT NULL,
    FECHA VARCHAR(50) DEFAULT 'NO HECHA',
    NOTA VARCHAR(10) DEFAULT '--',
    OBSERVACION VARCHAR(100),
    IMPORTANTE BOOLEAN DEFAULT 0,
    FASE_FK INTEGER NOT NULL,
    ACTIVIDAD_FK INTEGER NOT NULL,
    COD_ACTIVIDAD_FK INTEGER NOT NULL,

    FOREIGN KEY (FASE_FK) REFERENCES FASE(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ACTIVIDAD_FK) REFERENCES ACTIVIDAD(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COD_ACTIVIDAD_FK) REFERENCES COD_ACTIVIDAD(ID) ON DELETE CASCADE ON UPDATE CASCADE
);  

